### ISSUE TITLE
E4 - Backend - Requisições para listagem de grupos e posts de grupos

### ISSUE THREAD

**Issue by JP-Colafati** [wandsu/burnhop-server#26]
- [x] #25 Listagem de todos os grupos
- [x] #23 Listagem de posts relacionados ao grupo
- [x] #21 Listagem de grupos relacionados ao usuário
- [x] #20 Adicionar usuário a um grupo
- [x] #19 Retornar grupo por nome
